-- Plain-language, one-sentence explanation per scoring criterion, generated by
-- Claude alongside the score, so non-sales-expert managers understand what each
-- criterion in "Оцінка по критеріях" actually measures.
-- Run once in the Supabase SQL editor.

alter table public.ai_analysis
  add column if not exists criteria_explanations jsonb;
